from app.static_analysis.context_resolver import ContextResolver

def test_context_resolver_test_files():
    res1 = ContextResolver.resolve("tests/test_api.py")
    assert res1["is_test_file"] is True
    assert res1["is_config_file"] is False

    res2 = ContextResolver.resolve("app/test_helpers.py")
    assert res2["is_test_file"] is True

    res3 = ContextResolver.resolve("app/main.py")
    assert res3["is_test_file"] is False

def test_context_resolver_config_files():
    res1 = ContextResolver.resolve("config.py")
    assert res1["is_config_file"] is True

    res2 = ContextResolver.resolve("app/core/settings.py")
    assert res2["is_config_file"] is True

    res3 = ContextResolver.resolve("setup.py")
    assert res3["is_config_file"] is True

def test_context_resolver_migration_files():
    res1 = ContextResolver.resolve("migrations/versions/abc_123.py")
    assert res1["is_migration_file"] is True

    res2 = ContextResolver.resolve("env.py")
    assert res2["is_migration_file"] is True

def test_context_resolver_generated_files():
    res1 = ContextResolver.resolve("generated_code.py")
    assert res1["is_generated_file"] is True

    # Test file header content check
    code_with_header = "# Generated by the protocol buffer compiler. DO NOT EDIT!\nimport sys"
    res2 = ContextResolver.resolve("app/protos/message.py", code=code_with_header)
    assert res2["is_generated_file"] is True
