from pydantic import BaseModel, Field
from typing import Dict, Any, List, Optional
from app.analysis.RAG.context_management.merger import ContextMerger, MergedContext
from app.analysis.RAG.context_management.prioritizer import ContextPrioritizer
from app.analysis.RAG.token_management.budget import TokenBudgetManager, TokenBudget
from app.analysis.RAG.examples.selector import ExampleSelector
from app.analysis.RAG.formatting.formatters import PromptFormatter
from app.analysis.RAG.validation.validator import PromptValidator, ValidationResult
from app.analysis.RAG.templates.template_engine import TemplateEngine, PromptTemplate

class FinalPrompt(BaseModel):
    """Model representing the final prompt generated by the PromptBuilder."""
    system_instruction: str = Field(description="The system instructions for the LLM")
    user_prompt: str = Field(description="The formulated user prompt including context")
    template_name: str = Field(description="The name of the template used")
    output_format: str = Field(description="The requested output format")
    estimated_tokens: int = Field(description="Estimated token count of the prompt")
    validation_result: Any = Field(description="Result of prompt validation")
    sources: List[str] = Field(default_factory=list, description="List of source files or context identifiers used")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional metadata")

class PromptBuilder:
    """Master orchestrator for building prompts."""
    
    def __init__(self):
        self.context_merger = ContextMerger()
        self.context_prioritizer = ContextPrioritizer()
        self.token_budget_manager = TokenBudgetManager()
        self.template_engine = TemplateEngine()
        self.example_selector = ExampleSelector()
        self.prompt_formatter = PromptFormatter()
        self.prompt_validator = PromptValidator()

    def build_prompt(
        self, 
        analysis_findings: List[Dict[str, Any]], 
        retrieved_context: Any, 
        repo_context: Optional[Dict[str, Any]] = None, 
        template_name: str = "mixed_review", 
        output_format: str = "json", 
        max_tokens: int = 16000
    ) -> FinalPrompt:
        """Orchestrates the construction of a complete prompt for the LLM."""
        
        # 1. Retrieve the base template
        template = self.template_engine.get_template(template_name)
        
        # 2. Merge Context (deduplicating & categorizing)
        merged: MergedContext = self.context_merger.merge_all(
            analysis_findings=analysis_findings,
            retrieved_context=retrieved_context,
            repo_context=repo_context,
        )

        # 3. Prioritize Findings & Knowledge
        prioritized_findings = self.context_prioritizer.prioritize_findings(
            merged.critical_findings + merged.security_findings + merged.other_findings
        )
        prioritized_knowledge = self.context_prioritizer.prioritize_knowledge(
            merged.official_knowledge + merged.framework_knowledge + merged.general_knowledge
        )

        # 4. Format context sections
        context_blocks: Dict[str, str] = {}

        if repo_context:
            repo_text = []
            for k, v in repo_context.items():
                repo_text.append(f"- **{k}**: {v}")
            context_blocks["Repository Context"] = "\n".join(repo_text)

        if prioritized_findings:
            findings_text = []
            for f in prioritized_findings:
                title = f.get("title", f.get("description", "Finding"))
                sev = f.get("severity", "INFO")
                file_p = f.get("file", f.get("file_path", ""))
                line_no = f.get("line", f.get("line_number", ""))
                findings_text.append(f"- **[{sev}] {title}** ({file_p}:{line_no})")
            context_blocks["Critical Findings"] = "\n".join(findings_text)

        if hasattr(retrieved_context, "formatted_prompt_context") and retrieved_context.formatted_prompt_context:
            context_blocks["Retrieved Knowledge"] = retrieved_context.formatted_prompt_context
        elif prioritized_knowledge:
            knowledge_text = []
            for k in prioritized_knowledge:
                knowledge_text.append(f"### {getattr(k, 'title', str(k))}\n{getattr(k, 'content', '')}")
            context_blocks["Retrieved Knowledge"] = "\n\n".join(knowledge_text)

        # 5. Extract vulnerability types & select relevant examples
        vuln_types = [f.get("category", "") for f in analysis_findings if f.get("category")]
        framework = repo_context.get("framework", "") if repo_context else ""
        examples = self.example_selector.select_examples(vuln_types, framework=framework, max_examples=2)

        if examples:
            ex_text = []
            for ex in examples:
                ex_text.append(f"#### Example: {ex.title}\nBad:\n```python\n{ex.bad_code}\n```\nGood:\n```python\n{ex.good_code}\n```")
            context_blocks["Relevant Examples"] = "\n\n".join(ex_text)

        # 6. Render Template
        system_prompt, user_prompt = self.template_engine.render_template(
            template, context_blocks, output_format
        )

        # 7. Token budgeting & pruning if needed
        budget = TokenBudget(max_prompt_tokens=max_tokens)
        full_text = system_prompt + user_prompt
        estimated_tokens = self.token_budget_manager.estimate_tokens(full_text)

        if estimated_tokens > max_tokens:
            user_prompt = self.token_budget_manager.prune_text_to_budget(user_prompt, max_tokens - 1000)
            estimated_tokens = self.token_budget_manager.estimate_tokens(system_prompt + user_prompt)

        # 8. Validate Prompt
        val_result: ValidationResult = self.prompt_validator.validate_prompt(system_prompt, user_prompt, max_tokens)

        # 9. Collect sources
        sources = list(merged.source_attributions)

        return FinalPrompt(
            system_instruction=system_prompt,
            user_prompt=user_prompt,
            template_name=template_name,
            output_format=output_format,
            estimated_tokens=estimated_tokens,
            validation_result=val_result,
            sources=sources,
            metadata={"max_tokens": max_tokens, "findings_count": len(analysis_findings)},
        )
