import os
from typing import Dict, Any

class ContextResolver:
    """
    Resolves filename and content metadata to identify special file categories.
    Helps reduce noise and calibrate confidence scores for specific environments.
    """

    @staticmethod
    def resolve(file_path: str, code: str = "") -> Dict[str, bool]:
        """
        Determines file categories based on paths, naming conventions, and file headers.
        """
        norm_path = file_path.replace("\\", "/").lower()
        basename = os.path.basename(norm_path)

        # 1. Test File Heuristics
        is_test_file = (
            basename.startswith("test_") 
            or basename.endswith("_test.py") 
            or "/tests/" in norm_path 
            or norm_path.startswith("tests/")
            or "/test/" in norm_path
            or norm_path.startswith("test/")
        )

        # 2. Configuration File Heuristics
        is_config_file = (
            basename in ("config.py", "settings.py", "setup.py", "conftest.py") 
            or "configuration" in basename
        )

        # 3. Migration File Heuristics
        is_migration_file = (
            "/migrations/" in norm_path 
            or norm_path.startswith("migrations/")
            or basename == "env.py"  # Common for alembic
        )

        # 4. Generated File Heuristics
        is_generated_file = (
            "/generated/" in norm_path 
            or norm_path.startswith("generated/")
            or basename.startswith("generated_")
        )
        
        # Check file content header for generator comments
        if not is_generated_file and code:
            first_lines = [line.strip().lower() for line in code.splitlines()[:5] if line.strip()]
            for line in first_lines:
                if any(phrase in line for phrase in ("generated by", "auto-generated", "do not edit")):
                    is_generated_file = True
                    break

        return {
            "is_test_file": is_test_file,
            "is_config_file": is_config_file,
            "is_migration_file": is_migration_file,
            "is_generated_file": is_generated_file
        }
